# Normal Eq. Without Regularization

In [11]:
import numpy as np
wines = np.genfromtxt("HousingPrice.csv", delimiter=",", skip_header=1)
wines

array([[     nan, 4.20e+04, 5.85e+03, ...,      nan, 1.00e+00,      nan],
       [     nan, 3.85e+04, 4.00e+03, ...,      nan, 0.00e+00,      nan],
       [     nan, 4.95e+04, 3.06e+03, ...,      nan, 0.00e+00,      nan],
       ...,
       [     nan, 1.03e+05, 6.00e+03, ...,      nan, 1.00e+00,      nan],
       [     nan, 1.05e+05, 6.00e+03, ...,      nan, 1.00e+00,      nan],
       [     nan, 1.05e+05, 6.00e+03, ...,      nan, 1.00e+00,      nan]])

In [88]:
Price=[]
NoOfBathrooms=[]
NoOfBedrooms=[]
FloorArea=[]

for i in range(len(wines)):
    Price.append(wines[i][1])
for i in range(len(wines)):
    FloorArea.append(wines[i][2])
for i in range(len(wines)):
    NoOfBedrooms.append(wines[i][3])
for i in range(len(wines)):
    NoOfBathrooms.append(wines[i][4])


In [89]:
import math
m, n = wines.shape
n_train = math.floor(m*0.70)
n_test = m - n_train
n_train, n_test

(382, 164)

In [91]:
Col1 = [1] * len(FloorArea)
Col1

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [92]:
data = list(zip(Col1, FloorArea, NoOfBedrooms, NoOfBathrooms))
len(data), data

(546,
 [(1, 5850.0, 3.0, 1.0),
  (1, 4000.0, 2.0, 1.0),
  (1, 3060.0, 3.0, 1.0),
  (1, 6650.0, 3.0, 1.0),
  (1, 6360.0, 2.0, 1.0),
  (1, 4160.0, 3.0, 1.0),
  (1, 3880.0, 3.0, 2.0),
  (1, 4160.0, 3.0, 1.0),
  (1, 4800.0, 3.0, 1.0),
  (1, 5500.0, 3.0, 2.0),
  (1, 7200.0, 3.0, 2.0),
  (1, 3000.0, 2.0, 1.0),
  (1, 1700.0, 3.0, 1.0),
  (1, 2880.0, 3.0, 1.0),
  (1, 3600.0, 2.0, 1.0),
  (1, 3185.0, 2.0, 1.0),
  (1, 3300.0, 3.0, 1.0),
  (1, 5200.0, 4.0, 1.0),
  (1, 3450.0, 1.0, 1.0),
  (1, 3986.0, 2.0, 2.0),
  (1, 4785.0, 3.0, 1.0),
  (1, 4510.0, 4.0, 2.0),
  (1, 4000.0, 3.0, 1.0),
  (1, 3934.0, 2.0, 1.0),
  (1, 4960.0, 2.0, 1.0),
  (1, 3000.0, 2.0, 1.0),
  (1, 3800.0, 2.0, 1.0),
  (1, 4960.0, 2.0, 1.0),
  (1, 3000.0, 3.0, 1.0),
  (1, 4500.0, 3.0, 1.0),
  (1, 3500.0, 2.0, 1.0),
  (1, 3500.0, 4.0, 1.0),
  (1, 4000.0, 2.0, 1.0),
  (1, 4500.0, 2.0, 1.0),
  (1, 6360.0, 2.0, 1.0),
  (1, 4500.0, 2.0, 1.0),
  (1, 4032.0, 2.0, 1.0),
  (1, 5170.0, 3.0, 1.0),
  (1, 5400.0, 4.0, 2.0),
  (1, 3150.0, 2.0, 

In [93]:
X_train = data[:n_train]
len(X_train), X_train

(382,
 [(1, 5850.0, 3.0, 1.0),
  (1, 4000.0, 2.0, 1.0),
  (1, 3060.0, 3.0, 1.0),
  (1, 6650.0, 3.0, 1.0),
  (1, 6360.0, 2.0, 1.0),
  (1, 4160.0, 3.0, 1.0),
  (1, 3880.0, 3.0, 2.0),
  (1, 4160.0, 3.0, 1.0),
  (1, 4800.0, 3.0, 1.0),
  (1, 5500.0, 3.0, 2.0),
  (1, 7200.0, 3.0, 2.0),
  (1, 3000.0, 2.0, 1.0),
  (1, 1700.0, 3.0, 1.0),
  (1, 2880.0, 3.0, 1.0),
  (1, 3600.0, 2.0, 1.0),
  (1, 3185.0, 2.0, 1.0),
  (1, 3300.0, 3.0, 1.0),
  (1, 5200.0, 4.0, 1.0),
  (1, 3450.0, 1.0, 1.0),
  (1, 3986.0, 2.0, 2.0),
  (1, 4785.0, 3.0, 1.0),
  (1, 4510.0, 4.0, 2.0),
  (1, 4000.0, 3.0, 1.0),
  (1, 3934.0, 2.0, 1.0),
  (1, 4960.0, 2.0, 1.0),
  (1, 3000.0, 2.0, 1.0),
  (1, 3800.0, 2.0, 1.0),
  (1, 4960.0, 2.0, 1.0),
  (1, 3000.0, 3.0, 1.0),
  (1, 4500.0, 3.0, 1.0),
  (1, 3500.0, 2.0, 1.0),
  (1, 3500.0, 4.0, 1.0),
  (1, 4000.0, 2.0, 1.0),
  (1, 4500.0, 2.0, 1.0),
  (1, 6360.0, 2.0, 1.0),
  (1, 4500.0, 2.0, 1.0),
  (1, 4032.0, 2.0, 1.0),
  (1, 5170.0, 3.0, 1.0),
  (1, 5400.0, 4.0, 2.0),
  (1, 3150.0, 2.0, 

In [95]:
Y_train = Price[:n_train]
len(Y), Y

(382,
 [42000.0,
  38500.0,
  49500.0,
  60500.0,
  61000.0,
  66000.0,
  66000.0,
  69000.0,
  83800.0,
  88500.0,
  90000.0,
  30500.0,
  27000.0,
  36000.0,
  37000.0,
  37900.0,
  40500.0,
  40750.0,
  45000.0,
  45000.0,
  48500.0,
  65900.0,
  37900.0,
  38000.0,
  42000.0,
  42300.0,
  43500.0,
  44000.0,
  44500.0,
  44900.0,
  45000.0,
  48000.0,
  49000.0,
  51500.0,
  61000.0,
  61000.0,
  61700.0,
  67000.0,
  82000.0,
  54500.0,
  66500.0,
  70000.0,
  82000.0,
  92000.0,
  38000.0,
  44000.0,
  41000.0,
  43000.0,
  48000.0,
  54800.0,
  55000.0,
  57000.0,
  68000.0,
  95000.0,
  38000.0,
  25000.0,
  25245.0,
  56000.0,
  35500.0,
  30000.0,
  48000.0,
  48000.0,
  52000.0,
  54000.0,
  56000.0,
  60000.0,
  60000.0,
  67000.0,
  47000.0,
  70000.0,
  45000.0,
  51000.0,
  32500.0,
  34000.0,
  35000.0,
  36000.0,
  45000.0,
  47000.0,
  55000.0,
  63900.0,
  50000.0,
  35000.0,
  50000.0,
  43000.0,
  55500.0,
  57000.0,
  60000.0,
  78000.0,
  35000.0,
  44000.0,
  47

In [97]:
X_test = data[n_train+1:]
X_test

[(1, 7085.0, 3.0, 1.0),
 (1, 6600.0, 4.0, 2.0),
 (1, 6900.0, 3.0, 1.0),
 (1, 11460.0, 3.0, 1.0),
 (1, 7020.0, 3.0, 1.0),
 (1, 6540.0, 3.0, 1.0),
 (1, 8000.0, 3.0, 1.0),
 (1, 9620.0, 3.0, 1.0),
 (1, 10500.0, 3.0, 2.0),
 (1, 5020.0, 3.0, 1.0),
 (1, 7440.0, 3.0, 2.0),
 (1, 6600.0, 3.0, 1.0),
 (1, 7200.0, 3.0, 1.0),
 (1, 6710.0, 3.0, 2.0),
 (1, 6660.0, 4.0, 2.0),
 (1, 7000.0, 3.0, 1.0),
 (1, 7231.0, 3.0, 1.0),
 (1, 7410.0, 3.0, 1.0),
 (1, 7800.0, 3.0, 1.0),
 (1, 6825.0, 3.0, 1.0),
 (1, 6360.0, 3.0, 1.0),
 (1, 6600.0, 4.0, 2.0),
 (1, 6900.0, 3.0, 2.0),
 (1, 6600.0, 3.0, 1.0),
 (1, 6420.0, 3.0, 1.0),
 (1, 6600.0, 3.0, 2.0),
 (1, 6600.0, 3.0, 2.0),
 (1, 9000.0, 3.0, 1.0),
 (1, 6500.0, 3.0, 2.0),
 (1, 6360.0, 3.0, 2.0),
 (1, 5300.0, 3.0, 1.0),
 (1, 2850.0, 3.0, 2.0),
 (1, 6400.0, 3.0, 1.0),
 (1, 11175.0, 3.0, 1.0),
 (1, 6750.0, 2.0, 1.0),
 (1, 7500.0, 4.0, 2.0),
 (1, 6000.0, 3.0, 1.0),
 (1, 10240.0, 2.0, 1.0),
 (1, 5136.0, 3.0, 1.0),
 (1, 3400.0, 3.0, 1.0),
 (1, 2880.0, 3.0, 1.0),
 (1, 3840.0,

In [99]:
Y_test = Price[n_train+1:]
Y_test

[74700.0,
 78000.0,
 78900.0,
 83900.0,
 85000.0,
 85000.0,
 86000.0,
 86900.0,
 94500.0,
 96000.0,
 106000.0,
 72000.0,
 74500.0,
 77000.0,
 80750.0,
 82900.0,
 85000.0,
 92500.0,
 76000.0,
 77500.0,
 80000.0,
 80000.0,
 86000.0,
 87000.0,
 87500.0,
 89000.0,
 89900.0,
 90000.0,
 95000.0,
 112000.0,
 31900.0,
 52000.0,
 90000.0,
 100000.0,
 91700.0,
 174500.0,
 94700.0,
 68000.0,
 80000.0,
 61100.0,
 62900.0,
 65500.0,
 66000.0,
 49500.0,
 50000.0,
 53500.0,
 58550.0,
 64500.0,
 65000.0,
 69000.0,
 73000.0,
 75000.0,
 75000.0,
 132000.0,
 60000.0,
 65000.0,
 69000.0,
 51900.0,
 57000.0,
 65000.0,
 79500.0,
 72500.0,
 104900.0,
 114900.0,
 120000.0,
 58000.0,
 67000.0,
 67000.0,
 69000.0,
 73000.0,
 73500.0,
 74900.0,
 75000.0,
 79500.0,
 120900.0,
 44555.0,
 47000.0,
 47600.0,
 49000.0,
 49000.0,
 49000.0,
 49500.0,
 52000.0,
 54000.0,
 55000.0,
 55000.0,
 56000.0,
 60000.0,
 60500.0,
 50000.0,
 64900.0,
 93000.0,
 85000.0,
 61500.0,
 88500.0,
 88000.0,
 89000.0,
 89500.0,
 95000.0,
 

In [103]:
X_train_T = np.transpose(X_train)

In [104]:
theta = np.dot(np.dot(np.linalg.inv(np.dot(X_train_T, X_train)), X_train_T), Y)

In [105]:
theta

array([-4.89492370e+03,  5.93101241e+00,  5.52857201e+03,  1.90100176e+04])

In [106]:
theta.shape

(4,)

In [107]:
np.reshape(theta, (4,1))

array([[-4.89492370e+03],
       [ 5.93101241e+00],
       [ 5.52857201e+03],
       [ 1.90100176e+04]])

In [108]:
theta.shape

(4,)

In [109]:
theta[0]

-4894.923702349684

In [111]:
Y_pred = np.dot(X_test, theta)

In [112]:
Y_pred

array([ 72722.03279885,  94384.08134942,  71624.79550356,  98670.21207926,
        72336.5169924 ,  69489.63103706,  78148.90915121,  87757.14925047,
       111986.45772154,  60474.49217849,  93837.55975627,  69845.49178148,
        73404.09922565,  89507.92069919,  94739.94209384,  72217.89674426,
        73587.96061026,  74649.61183111,  76962.70666982,  71179.96957304,
        68422.04880381,  94384.08134942,  90634.81305651,  69845.49178148,
        68777.90954822,  88855.50933443,  88855.50933443,  84079.92155816,
        88262.40809373,  87432.06635676,  62135.17565244,  66614.21280836,
        68659.28930009,  96979.87354328,  65206.57162752,  99721.99251568,
        66286.8843373 ,  85905.80492778,  61162.4896177 ,  50866.25207923,
        47782.12562761,  53475.89753829,  42194.24348855,  56725.22388558,
        46001.95345381,  45812.16105679,  52052.45456062,  46049.40155307,
        62253.79590058,  66524.12483358,  92845.08944392,  80521.31411399,
        86673.76522039,  

In [113]:
Y_pred.shape

(163,)

In [122]:
error = 0
for i in range(n_test-1):
    error += abs((Y_test[i] - Y_pred[i])/Y_test[i])
error = error/n_test
error

0.18531429795318305

In [126]:
print("ERROR WITHOPUT REGULARIZATION: ", error)

ERROR WITHOPUT REGULARIZATION:  0.18531429795318305


# Adding Regularization

In [123]:
L = np.identity(4, dtype=float)
L[0][0] = 0
L

array([[0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [124]:
B = np.dot(X_train_T, Y_train)
A = np.dot(X_train_T, X_train)

In [125]:
error_reg = error
for i in range(10):
    theta = np.dot(np.add(A, i*L), B)
    Y_pred = np.dot(X_test, theta)
    error_t=0;
    for i in range(n_test-1):
        error_t += abs((Y_test[i] - Y_pred[i])/Y_test[i])
    error_t = error/n_test
    error_reg = min(error_reg, error_t)

error_reg    

0.001129965231421848

In [127]:
print("ERROR WITH REGULARIZATION: ", error_reg)

ERROR WITH REGULARIZATION:  0.001129965231421848
