In [455]:
import numpy as np
import pandas as pd
import random
import math

df = pd.read_csv("HousingPrice.csv")

Price = df['price']
FloorArea = df['lotsize']
NoOfBedrooms = df['bedrooms']
NoOfBathrooms = df['bathrms']

## Feature Scaling on FloorArea

In [456]:
FloorAreaMean = np.mean(FloorArea)
FloorAreaMin = min(FloorArea)
FloorAreaMax = max(FloorArea)
FloorAreaScaled = (FloorArea - FloorAreaMean)/(FloorAreaMax - FloorAreaMin)
FloorArea, FloorAreaScaled

(0      5850
 1      4000
 2      3060
 3      6650
 4      6360
        ... 
 541    4800
 542    6000
 543    6000
 544    6000
 545    6000
 Name: lotsize, Length: 546, dtype: int64,
 0      0.048092
 1     -0.079056
 2     -0.143661
 3      0.103075
 4      0.083143
          ...   
 541   -0.024073
 542    0.058401
 543    0.058401
 544    0.058401
 545    0.058401
 Name: lotsize, Length: 546, dtype: float64)

In [457]:
FloorAreaScaled.shape

(546,)

##  Creating useful Valiables

In [458]:
n, m = df.shape
n, m

(546, 13)

In [459]:
n_train = math.floor(n * 0.70)
n_test = n - n_train
n_train, n_test

(382, 164)

In [460]:
col = [1] * n
data_without_scaling = list(zip(col,FloorArea,NoOfBedrooms,NoOfBathrooms))
data_scaling = list(zip(col,FloorAreaScaled,NoOfBedrooms,NoOfBathrooms))
len(data_without_scaling), len(data_scaling)

(546, 546)

In [461]:
# X_train, Y_train, X_test, Y_test without scaling
X_train = data_without_scaling[:n_train]
Y_train = Price[:n_train]

X_test = data_without_scaling[n_train+1:]
Y_test = Price[n_train+1:]

# X_train, Y_train, X_test, Y_test with scaling
X_train_scaling = data_scaling[:n_train]
Y_train_scaling = Price[:n_train]

X_test_scaling = data_scaling[n_train+1:]
Y_test_scaling = Price[n_train+1:]

In [462]:
X_train, X_train_scaling

([(1, 5850, 3, 1),
  (1, 4000, 2, 1),
  (1, 3060, 3, 1),
  (1, 6650, 3, 1),
  (1, 6360, 2, 1),
  (1, 4160, 3, 1),
  (1, 3880, 3, 2),
  (1, 4160, 3, 1),
  (1, 4800, 3, 1),
  (1, 5500, 3, 2),
  (1, 7200, 3, 2),
  (1, 3000, 2, 1),
  (1, 1700, 3, 1),
  (1, 2880, 3, 1),
  (1, 3600, 2, 1),
  (1, 3185, 2, 1),
  (1, 3300, 3, 1),
  (1, 5200, 4, 1),
  (1, 3450, 1, 1),
  (1, 3986, 2, 2),
  (1, 4785, 3, 1),
  (1, 4510, 4, 2),
  (1, 4000, 3, 1),
  (1, 3934, 2, 1),
  (1, 4960, 2, 1),
  (1, 3000, 2, 1),
  (1, 3800, 2, 1),
  (1, 4960, 2, 1),
  (1, 3000, 3, 1),
  (1, 4500, 3, 1),
  (1, 3500, 2, 1),
  (1, 3500, 4, 1),
  (1, 4000, 2, 1),
  (1, 4500, 2, 1),
  (1, 6360, 2, 1),
  (1, 4500, 2, 1),
  (1, 4032, 2, 1),
  (1, 5170, 3, 1),
  (1, 5400, 4, 2),
  (1, 3150, 2, 2),
  (1, 3745, 3, 1),
  (1, 4520, 3, 1),
  (1, 4640, 4, 1),
  (1, 8580, 5, 3),
  (1, 2000, 2, 1),
  (1, 2160, 3, 1),
  (1, 3040, 2, 1),
  (1, 3090, 3, 1),
  (1, 4960, 4, 1),
  (1, 3350, 3, 1),
  (1, 5300, 5, 2),
  (1, 4100, 4, 1),
  (1, 9166, 

## Function to find slope

In [463]:
def Slope(theta, X, Y, ind):
	slope = 0
	for i in range(len(X)):
		itr = 0
		for j in range(len(theta)):
			itr = itr + theta[j] * X[i][j]
		slope += (itr - Y[i]) * X[i][ind]
	return slope

# Using batch gradient without feature scaling

In [464]:
lr = 0.0000001
theta = np.zeros((1,4))
theta

array([[0., 0., 0., 0.]])

In [465]:
for i in range(1000):
    temp = theta.copy()
    for j in range(len(theta)):
        temp[j] -= (lr/n_train) * Slope(theta, X_train, Y_train, j)
    theta = temp.copy()
np.reshape(theta, (4,1))
theta

array([[6.39331599, 6.39331599, 6.39331599, 6.39331599]])

In [466]:
theta = theta.reshape((4,1))
theta.shape

(4, 1)

In [467]:
Y_pred = np.dot(X_test, theta)

In [470]:
error = 0
for i in range(n_test-1):
    error += abs((Y_test.iloc[i] - Y_pred[i][0])/Y_test.iloc[i])
error /= n_test
error

0.5017827139124416

# Using batch gradient with feature scaling

In [471]:
lr = 0.002
theta = np.zeros((1,4))
theta

array([[0., 0., 0., 0.]])

In [472]:
for i in range(100):
    temp = theta.copy()
    for j in range(len(theta)):
        temp[j] -= (lr/n_train) * Slope(theta, X_train_scaling, Y_train_scaling, j)
    theta = temp.copy()
np.reshape(theta, (4,1))
theta

array([[11600.1768945, 11600.1768945, 11600.1768945, 11600.1768945]])

In [473]:
theta = theta.reshape((4,1))
theta.shape

(4, 1)

In [475]:
Y_pred = np.dot(X_test_scaling, theta)
error = 0
for i in range(n_test-1):
    error += abs((Y_test.iloc[i] - Y_pred[i][0])/Y_test.iloc[i])
error /= n_test
error

0.21904970666282153

# Using Stochastic gradient without feature scaling

In [476]:
def SlopeStoch(theta,X,Y,ind):
	itr = 0
	for j in range(len(theta)):
		itr = itr + theta[j] * X[j]
	return (itr - Y) * X[ind]

In [477]:
lr = 0.002
theta = [0,0,0,0]
theta

[0, 0, 0, 0]

In [478]:
for iter in range(10):
	for i in range(len(X_train)):
		tempp = theta.copy()
		for j in range(len(temp)):
			tempp[j] = tempp[j] - (lr * SlopeStoch(theta, X_train[i], Y_train[i], j))
		theta = tempp.copy()
theta

[66269.83327489161, 0, 0, 0]

In [479]:
Y_pred = np.dot(X_test, theta)

In [481]:
error = 0
for i in range(n_test-1):
    error += abs((Y_test.iloc[i] - Y_pred[i])/Y_test.iloc[i])
error = error/n_test
error

0.22545121631832774

# Using Stochastic gradient with feature scaling

In [493]:
lr = 0.000003
theta = [0,0,0,0]
theta

[0, 0, 0, 0]

In [494]:
for iter in range(10):
	for i in range(len(X_train_scaling)):
		tempp = theta.copy()
		for j in range(4):
			tempp[j] = tempp[j] - (lr * (SlopeStoch(theta, X_train_scaling[i], Y_train_scaling[i], j)))
		theta = tempp.copy()
theta

[685.7678766874692, 5.893634578291078, 2100.5757460708946, 958.624260916667]

In [495]:
Y_pred = np.dot(X_test, theta)

In [496]:
error = 0
for i in range(n_test-1):
    error += abs((Y_test.iloc[i] - Y_pred[i])/Y_test.iloc[i])
error = error/n_test
error

0.43491568188402463

# Using Minibatch gradient without feature scaling for batch size = 20

In [497]:
BatchSize = 20;
lr = 0.000000001
theta = [0, 0, 0, 0]

In [498]:
Batches = math.ceil(len(X_train) / BatchSize)
Batches

20

In [499]:
equallyDiv = False
if (len(Y_train) % BatchSize == 0):
	equallyDiv = True;

In [500]:
for epoch in range(30):
	for batch in range(Batches):
		temp = [0, 0, 0, 0]
		for j in range(len(theta)):
			for i in range(BatchSize):
				if (batch * BatchSize + i == len(X_train)):
					break
				pred = 0.0
				for wj in range(len(theta)):
					pred += theta[wj] * X_train[batch * BatchSize + i][wj]
				pred -= Y_train[batch * BatchSize + i]
				pred *= X_train[batch * BatchSize + i][j]
				temp[j] += pred;

		if (not equallyDiv and batch == Batches - 1):
			for j in range(len(temp)):
				theta[j] -= (temp[j] / (len(Y_train) % BatchSize)) * lr
		else:
			for j in range(len(temp)):
				theta[j] -= (temp[j] / BatchSize) * lr

In [501]:
theta

[0.0046877609132215045,
 12.601042025875056,
 0.0163743583721716,
 0.00829941066841396]

In [502]:
Y_pred = np.dot(X_test, theta)

In [504]:
error = 0
for i in range(n_test-1):
    error += abs((Y_test.iloc[i] - Y_pred[i])/Y_test.iloc[i])
error = error/n_test
error

0.2984284750975368

# Using Minibatch gradient with feature scaling for batch size = 20

In [505]:
BatchSize = 20;
lr = 0.00002
theta = [0, 0, 0, 0]

In [506]:
Batches = math.ceil(len(X_train_scaling) / BatchSize)
equallyDiv = False
if (len(Y_train_scaling) % BatchSize == 0):
	equallyDiv = True;

In [507]:
for epoch in range(30):
	for batch in range(Batches):
		temp = [0, 0, 0, 0]
		for j in range(len(theta)):
			for i in range(BatchSize):
				if (batch * BatchSize + i == len(X_train_scaling)):
					break
				pred = 0.0
				for wj in range(len(theta)):
					pred += theta[wj] * X_train_scaling[batch * BatchSize + i][wj]
				pred -= Y_train_scaling[batch * BatchSize + i]
				pred *= X_train_scaling[batch * BatchSize + i][j]
				temp[j] += pred;

		if (not equallyDiv and batch == Batches - 1):
			for j in range(len(temp)):
				theta[j] -= (temp[j] / (len(Y_train_scaling) % BatchSize)) * lr
		else:
			for j in range(len(temp)):
				theta[j] -= (temp[j] / BatchSize) * lr

In [508]:
theta

[737.0312224997455, 15.818366536564183, 2280.3034424443404, 1034.8610259078293]

In [509]:
Y_pred = np.dot(X_test, theta)

In [511]:
error = 0
for i in range(n_test-1):
    error += abs((Y_test.iloc[i] - Y_pred[i])/Y_test.iloc[i])
error = error/n_test
error

0.43735434315618654